# Generated by Django 4.2.21 on 2025-05-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constraints',
            name='dp_plus_first_plus_second_plus_third_pmt',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='constraints',
            name='dp_plus_first_plus_second_pmt',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
