# Generated by Django 4.2.21 on 2025-05-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0002_constraints_dp_plus_first_plus_second_plus_third_pmt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrequest',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
