# Generated by Django 4.2.21 on 2025-05-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0003_salesrequest_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrequest',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
