# Generated by Django 4.2.21 on 2025-05-29 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0004_salesrequest_client_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectWebConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_maintenance', models.BooleanField(default=False)),
                ('show_gas', models.BooleanField(default=False)),
                ('show_discount', models.BooleanField(default=False)),
                ('show_payment_frequency', models.BooleanField(default=False)),
                ('show_currecny', models.BooleanField(default=False)),
                ('show_lead_name', models.BooleanField(default=False)),
                ('has_multiple_dp', models.BooleanField(default=False)),
                ('default_timer_in_minutes', models.IntegerField(blank=True, null=True)),
                ('period_between_DPs', models.IntegerField(blank=True, null=True)),
                ('period_between_DP_and_intsallment', models.IntegerField(blank=True, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ToP.project')),
            ],
        ),
    ]
