# Generated by Django 4.2.21 on 2025-05-29 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0005_projectwebconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrequest',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ToP.project'),
        ),
    ]
