# Generated by Django 5.1.6 on 2025-06-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0006_salesrequest_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectwebconfiguration',
            name='show_standerd_price',
            field=models.BooleanField(default=False),
        ),
    ]
