# Generated by Django 4.2.21 on 2025-06-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0007_projectwebconfiguration_show_standerd_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectconfiguration',
            name='variable_delivery_date',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
