# Generated by Django 4.2.21 on 2025-06-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0009_projectextendedpayments'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_dp1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_dp2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
