# Generated by Django 4.2.21 on 2025-06-13 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0012_constraints_dp_plus_first_plus_second_plus_third_plus_forth_pmt'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectextendedpayments',
            name='year',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='projectextendedpayments',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToP.project'),
        ),
        migrations.AlterUniqueTogether(
            name='projectextendedpayments',
            unique_together={('project', 'year')},
        ),
    ]
