# Generated by Django 4.2.21 on 2025-06-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0013_projectextendedpayments_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrequest',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesrequest',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
