# Generated by Django 4.2.21 on 2025-06-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0014_salesrequest_final_price_salesrequest_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrequest',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
    ]
