# Generated by Django 4.2.21 on 2025-06-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0015_alter_salesrequest_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrequest',
            name='is_fake',
            field=models.BooleanField(default=False),
        ),
    ]
