# Generated by Django 4.2.21 on 2025-06-16 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0016_salesrequest_is_fake'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRequestAnalytical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100)),
                ('erp_unit_code', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('discount', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_fake', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ToP.company')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ToP.project')),
                ('sales_man', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_requests_analytical', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_requests_analytical', to='ToP.unit')),
            ],
        ),
    ]
