# Generated by Django 4.2.21 on 2025-06-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0017_salesrequestanalytical'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectextendedpayments',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='scheme',
            field=models.CharField(default='flat', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='projectextendedpayments',
            unique_together={('project', 'year', 'scheme')},
        ),
    ]
