# Generated by Django 4.2.21 on 2025-06-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0018_alter_projectextendedpayments_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaspolicyoffsets',
            name='offset_value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='maintenancepolicyoffsets',
            name='offset_value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
