# Generated by Django 4.2.21 on 2025-06-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0019_alter_gaspolicyoffsets_offset_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancepolicy',
            name='split_two_one_on_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
