# Generated by Django 4.2.21 on 2025-06-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0020_maintenancepolicy_split_two_one_on_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectconfiguration',
            name='default_scheme',
            field=models.CharField(default='Flat', max_length=100),
        ),
    ]
