# Generated by Django 4.2.21 on 2025-06-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0021_projectconfiguration_default_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectwebconfiguration',
            name='show_payment_scheme',
            field=models.BooleanField(default=False),
        ),
    ]
