# Generated by Django 4.2.21 on 2025-06-27 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0022_projectwebconfiguration_show_payment_scheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDiscountRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=1)),
                ('discount_rate_1', models.FloatField(blank=True, null=True)),
                ('discount_rate_2', models.FloatField(blank=True, null=True)),
                ('discount_rate_3', models.FloatField(blank=True, null=True)),
                ('discount_rate_4', models.FloatField(blank=True, null=True)),
                ('discount_rate_5', models.FloatField(blank=True, null=True)),
                ('discount_rate_6', models.FloatField(blank=True, null=True)),
                ('discount_rate_7', models.FloatField(blank=True, null=True)),
                ('discount_rate_8', models.FloatField(blank=True, null=True)),
                ('discount_rate_9', models.FloatField(blank=True, null=True)),
                ('discount_rate_10', models.FloatField(blank=True, null=True)),
                ('discount_rate_11', models.FloatField(blank=True, null=True)),
                ('discount_rate_12', models.FloatField(blank=True, null=True)),
                ('discount_rate_13', models.FloatField(blank=True, null=True)),
                ('discount_rate_14', models.FloatField(blank=True, null=True)),
                ('discount_rate_15', models.FloatField(blank=True, null=True)),
                ('discount_rate_16', models.FloatField(blank=True, null=True)),
                ('discount_rate_17', models.FloatField(blank=True, null=True)),
                ('discount_rate_18', models.FloatField(blank=True, null=True)),
                ('discount_rate_19', models.FloatField(blank=True, null=True)),
                ('discount_rate_20', models.FloatField(blank=True, null=True)),
                ('discount_rate_21', models.FloatField(blank=True, null=True)),
                ('discount_rate_22', models.FloatField(blank=True, null=True)),
                ('discount_rate_23', models.FloatField(blank=True, null=True)),
                ('discount_rate_24', models.FloatField(blank=True, null=True)),
                ('discount_rate_25', models.FloatField(blank=True, null=True)),
                ('discount_rate_26', models.FloatField(blank=True, null=True)),
                ('discount_rate_27', models.FloatField(blank=True, null=True)),
                ('discount_rate_28', models.FloatField(blank=True, null=True)),
                ('discount_rate_29', models.FloatField(blank=True, null=True)),
                ('discount_rate_30', models.FloatField(blank=True, null=True)),
                ('discount_rate_31', models.FloatField(blank=True, null=True)),
                ('discount_rate_32', models.FloatField(blank=True, null=True)),
                ('discount_rate_33', models.FloatField(blank=True, null=True)),
                ('discount_rate_34', models.FloatField(blank=True, null=True)),
                ('discount_rate_35', models.FloatField(blank=True, null=True)),
                ('discount_rate_36', models.FloatField(blank=True, null=True)),
                ('discount_rate_37', models.FloatField(blank=True, null=True)),
                ('discount_rate_38', models.FloatField(blank=True, null=True)),
                ('discount_rate_39', models.FloatField(blank=True, null=True)),
                ('discount_rate_40', models.FloatField(blank=True, null=True)),
                ('discount_rate_41', models.FloatField(blank=True, null=True)),
                ('discount_rate_42', models.FloatField(blank=True, null=True)),
                ('discount_rate_43', models.FloatField(blank=True, null=True)),
                ('discount_rate_44', models.FloatField(blank=True, null=True)),
                ('discount_rate_45', models.FloatField(blank=True, null=True)),
                ('discount_rate_46', models.FloatField(blank=True, null=True)),
                ('discount_rate_47', models.FloatField(blank=True, null=True)),
                ('discount_rate_48', models.FloatField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToP.project')),
            ],
            options={
                'unique_together': {('project', 'year')},
            },
        ),
    ]
