# Generated by Django 4.2.21 on 2025-06-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0023_projectdiscountrates'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_11',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_12',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_13',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_14',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_15',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_16',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_17',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_18',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_19',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_20',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_21',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_22',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_23',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_24',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_25',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_26',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_27',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_28',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_29',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_30',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_31',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_32',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_33',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_34',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_35',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_36',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_37',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_38',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_39',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_40',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_41',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_42',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_43',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_44',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_45',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_46',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_47',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_48',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_8',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_9',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_dp1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='cumulative_discounted_dp2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_11',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_12',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_13',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_14',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_15',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_16',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_17',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_18',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_19',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_20',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_21',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_22',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_23',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_24',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_25',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_26',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_27',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_28',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_29',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_30',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_31',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_32',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_33',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_34',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_35',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_36',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_37',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_38',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_39',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_40',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_41',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_42',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_43',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_44',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_45',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_46',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_47',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_48',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_8',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_9',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_dp1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='discounted_value_dp2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_11',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_12',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_13',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_14',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_15',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_16',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_17',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_18',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_19',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_20',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_21',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_22',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_23',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_24',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_25',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_26',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_27',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_28',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_29',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_30',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_31',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_32',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_33',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_34',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_35',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_36',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_37',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_38',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_39',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_40',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_41',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_42',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_43',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_44',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_45',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_46',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_47',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_48',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_8',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_9',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_dp1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='cumulative_discounted_dp2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_11',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_12',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_13',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_14',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_15',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_16',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_17',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_18',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_19',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_20',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_21',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_22',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_23',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_24',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_25',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_26',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_27',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_28',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_29',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_30',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_31',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_32',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_33',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_34',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_35',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_36',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_37',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_38',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_39',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_40',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_41',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_42',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_43',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_44',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_45',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_46',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_47',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_48',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_8',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_9',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_dp1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='discounted_value_dp2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
