# Generated by Django 4.2.21 on 2025-06-29 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0024_projectextendedpayments_cumulative_discounted_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdiscountrates',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ToP.project'),
        ),
        migrations.AlterField(
            model_name='projectextendedpayments',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ToP.project'),
        ),
        migrations.RemoveField(
            model_name='projectdiscountrates',
            name='year',
        ),
        migrations.RemoveField(
            model_name='projectextendedpayments',
            name='scheme',
        ),
        migrations.RemoveField(
            model_name='projectextendedpayments',
            name='year',
        ),
    ]
