# Generated by Django 4.2.21 on 2025-06-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0025_alter_projectdiscountrates_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdiscountrates',
            name='delivery_index',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='projectextendedpayments',
            name='delivery_index',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='projectstanderdpayments',
            name='delivery_index',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
