# Generated by Django 4.2.21 on 2025-07-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0026_projectdiscountrates_delivery_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('CompanyUser', 'Company User'), ('Developer', 'Developer'), ('Manager', 'Company Manager'), ('BusinessTeam', 'Business Team'), ('CompanyController', 'Company Controller')], default='Company_User', max_length=100),
        ),
    ]
