# Generated by Django 4.2.21 on 2025-07-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0029_marketprojectdeveloper_marketprojectlocation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketUnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
