# Generated by Django 4.2.21 on 2025-07-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0030_marketunittype'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketUnitData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('developer_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('asset_type', models.CharField(max_length=255)),
                ('unit_type', models.CharField(max_length=255)),
                ('bua', models.FloatField(blank=True, null=True)),
                ('land_area', models.FloatField(blank=True, null=True)),
                ('garden', models.FloatField(blank=True, null=True)),
                ('unit_price', models.FloatField(blank=True, null=True)),
                ('psm', models.FloatField(blank=True, null=True)),
                ('payment_yrs_raw', models.TextField(blank=True, null=True)),
                ('payment_yrs', models.CharField(blank=True, max_length=255, null=True)),
                ('down_payment', models.FloatField(blank=True, null=True)),
                ('delivery_percentage', models.FloatField(blank=True, null=True)),
                ('cash_discount', models.FloatField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('finishing_specs', models.CharField(blank=True, max_length=255, null=True)),
                ('maintenance', models.FloatField(blank=True, null=True)),
                ('phase', models.FloatField(blank=True, null=True)),
                ('date_of_update', models.DateField()),
                ('updated_by', models.TextField(blank=True, null=True)),
                ('source_of_info', models.TextField(blank=True, null=True)),
                ('months_from_update', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
