# Generated by Django 4.2.21 on 2025-07-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0031_marketunitdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketunitdata',
            name='asset_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='marketunitdata',
            name='date_of_update',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketunitdata',
            name='developer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='marketunitdata',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='marketunitdata',
            name='project_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='marketunitdata',
            name='unit_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
