# Generated by Django 4.2.21 on 2025-07-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0032_alter_marketunitdata_asset_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketunitdata',
            name='delivery_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
