# Generated by Django 4.2.21 on 2025-07-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0033_alter_marketunitdata_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketunitdata',
            name='date_of_update',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
