# Generated by Django 4.2.21 on 2025-07-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0034_alter_marketunitdata_date_of_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketunitdata',
            name='date_of_update',
            field=models.DateField(blank=True, null=True),
        ),
    ]
