# Generated by Django 4.2.21 on 2025-07-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0035_alter_marketunitdata_date_of_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketunitdata',
            name='dp_percentage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
