# Generated by Django 4.2.21 on 2025-07-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0036_marketunitdata_dp_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketproject',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='marketproject',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
