# Generated by Django 4.2.21 on 2025-08-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0038_projectextendedpaymentsspecialoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketproject',
            name='govern',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
