# Generated by Django 4.2.21 on 2025-08-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0040_remove_projectstanderdpayments_cumulative_discounted_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectwebconfiguration',
            name='additional_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='projectwebconfiguration',
            name='dp_for_additional_discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectwebconfiguration',
            name='show_additional_discount',
            field=models.BooleanField(default=False),
        ),
    ]
