# Generated by Django 4.2.21 on 2025-08-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0041_projectwebconfiguration_additional_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_native',
        ),
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('native', 'Native'), ('erp', 'ERP'), ('google_sheets', 'Google Sheets')], default='native', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='google_sheet_gid',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='google_sheet_title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='google_sheet_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ProjectDiscountRates',
        ),
    ]
