# Generated by Django 4.2.21 on 2025-09-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0042_remove_company_is_native_company_company_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectextendedpayments',
            name='disable_additional_discount',
            field=models.BooleanField(default=False),
        ),
    ]
