# Generated by Django 4.2.21 on 2025-09-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0043_projectextendedpayments_disable_additional_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectwebconfiguration',
            name='real_discount',
            field=models.BooleanField(default=False),
        ),
    ]
