# Generated by Django 4.2.21 on 2025-09-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0044_projectwebconfiguration_real_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectconfiguration',
            name='maximum_requests_per_sales',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of customer requests assigned per sales rep (e.g., per day).', null=True),
        ),
    ]
