# Generated by Django 4.2.21 on 2025-09-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0045_projectconfiguration_maximum_requests_per_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrequest',
            name='client_phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
