# Generated by Django 4.2.21 on 2025-09-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0046_salesrequest_client_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectwebconfiguration',
            name='show_lead_phone_number',
            field=models.BooleanField(default=False),
        ),
    ]
