# Generated by Django 4.2.21 on 2025-09-18 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0047_projectwebconfiguration_show_lead_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPremiumGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_groups', to='ToP.project')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'project')},
            },
        ),
        migrations.CreateModel(
            name='PricingPremiumSubgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.IntegerField(default=0)),
                ('premium_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='ToP.pricingpremiumgroup')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'premium_group')},
            },
        ),
    ]
