# Generated by Django 4.2.21 on 2025-09-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0048_pricingpremiumgroup_pricingpremiumsubgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingpremiumsubgroup',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
