# Generated by Django 4.2.21 on 2025-09-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0049_alter_pricingpremiumsubgroup_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='special_premiums_discounts',
            new_name='special_discounts',
        ),
        migrations.AddField(
            model_name='unit',
            name='special_premiums',
            field=models.TextField(blank=True, null=True),
        ),
    ]
