# Generated by Django 4.2.21 on 2025-09-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0050_rename_special_premiums_discounts_unit_special_discounts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='phasing',
            field=models.TextField(blank=True, null=True),
        ),
    ]
