# Generated by Django 4.2.21 on 2025-09-21 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0051_unit_phasing'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_model', models.CharField(max_length=255)),
                ('bua_price_per_square_meter', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('extra_bua_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('extra_bua_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('terrace_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('terrace_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('terrace_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('penthouse_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('penthouse_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('extra_penthouse_price_per_square_meter', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('extra_penthouse_percentage_per_square_meter', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('roof_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('roof_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('extra_roof_price_price_per_square_meter', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('extra_roof_price_percentage_per_square_meter', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('land_price_per_square_meter', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('land_percentage_per_square_meter', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('extra_land_price_per_square_meter', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('extra_land_percentage_per_square_meter', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_criterias', to='ToP.project')),
            ],
            options={
                'unique_together': {('project', 'unit_model')},
            },
        ),
    ]
