# Generated by Django 4.2.21 on 2025-09-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0052_pricingcriteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectextendedpaymentsspecialoffer',
            name='constant_discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
