# Generated by Django 4.2.21 on 2025-10-05 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0053_projectextendedpaymentsspecialoffer_constant_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectextendedpaymentsspecialoffer',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToP.project'),
        ),
    ]
