# Generated by Django 4.2.21 on 2025-10-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0054_alter_projectextendedpaymentsspecialoffer_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='adj_contract_payment_plan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
