# Generated by Django 4.2.21 on 2025-11-16 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0055_unit_adj_contract_payment_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricingcriteria',
            old_name='extra_roof_price_percentage_per_square_meter',
            new_name='extra_roof_percentage_per_square_meter',
        ),
        migrations.RenameField(
            model_name='pricingcriteria',
            old_name='extra_roof_price_price_per_square_meter',
            new_name='extra_roof_price_per_square_meter',
        ),
    ]
