# Generated by Django 4.2.21 on 2025-11-18 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0056_rename_extra_roof_price_percentage_per_square_meter_pricingcriteria_extra_roof_percentage_per_square'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleServiceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=255)),
                ('private_key_id', models.CharField(max_length=255)),
                ('private_key', models.TextField()),
                ('client_email', models.EmailField(max_length=254)),
                ('client_id', models.CharField(max_length=255)),
                ('auth_uri', models.URLField(default='https://accounts.google.com/o/oauth2/auth')),
                ('token_uri', models.URLField(default='https://oauth2.googleapis.com/token')),
                ('auth_provider_x509_cert_url', models.URLField(default='https://www.googleapis.com/oauth2/v1/certs')),
                ('client_x509_cert_url', models.URLField()),
                ('universe_domain', models.CharField(default='googleapis.com', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_service_account', to='ToP.company')),
            ],
        ),
    ]
