# Generated by Django 4.2.21 on 2025-11-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0057_googleserviceaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectwebconfiguration',
            name='payment_schemes_to_show',
            field=models.JSONField(blank=True, default=list, help_text='List of payment schemes to show (Flat, Flat Back Loaded, Bullet, Bullet Back Loaded)'),
        ),
    ]
