# Generated by Django 4.2.21 on 2025-11-23 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0058_projectwebconfiguration_payment_schemes_to_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrequest',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_requests', to='ToP.unit'),
        ),
        migrations.AlterField(
            model_name='salesrequestanalytical',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_requests_analytical', to='ToP.unit'),
        ),
    ]
