# Generated by Django 4.2.21 on 2025-11-23 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0059_alter_salesrequest_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMasterplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='masterplans/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='masterplan', to='ToP.project')),
            ],
        ),
        migrations.CreateModel(
            name='UnitPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(max_length=50)),
                ('x_percent', models.DecimalField(decimal_places=3, max_digits=6)),
                ('y_percent', models.DecimalField(decimal_places=3, max_digits=6)),
                ('unit_type', models.CharField(choices=[('single', 'Single Unit'), ('building', 'Building')], default='single', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('masterplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_positions', to='ToP.projectmasterplan')),
            ],
            options={
                'unique_together': {('masterplan', 'unit_code')},
            },
        ),
    ]
