# Generated by Django 4.2.21 on 2025-11-23 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0060_projectmasterplan_unitposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitPositionChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(max_length=50)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_units', to='ToP.unitposition')),
            ],
        ),
    ]
