# Generated by Django 4.2.21 on 2025-11-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0061_unitpositionchild'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrequest',
            name='extended_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
