# Generated by Django 4.2.21 on 2025-12-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0062_salesrequest_extended_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectwebconfiguration',
            name='show_not_availables_units_for_sales',
            field=models.BooleanField(default=False, help_text='If True: Sales see ALL units. If False: Sales see ONLY Available units.'),
        ),
        migrations.AlterField(
            model_name='salesrequest',
            name='extended_minutes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
