# Generated by Django 4.2.21 on 2025-12-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0063_projectwebconfiguration_show_not_availables_units_for_sales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrequest',
            name='payment_plan_data',
            field=models.JSONField(blank=True, help_text='Stores the snapshot of payments, installments, and calculations.', null=True),
        ),
    ]
