# Generated by Django 4.2.21 on 2025-12-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0064_salesrequest_payment_plan_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='can_edit',
            field=models.BooleanField(default=False),
        ),
    ]
