# Generated by Django 4.2.21 on 2025-12-17 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0065_companyuser_can_edit'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_type', models.CharField(max_length=255)),
                ('unit_type', models.CharField(max_length=255)),
                ('unit_model', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='unit_layouts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to='ToP.project')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
