# Generated by Django 4.2.21 on 2025-12-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0066_unitlayout'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectwebconfiguration',
            name='discount_after_discount',
            field=models.BooleanField(default=True, help_text='If True: Apply discount on the discounted price. If False: Apply on original price.'),
        ),
    ]
