# Generated by Django 4.2.21 on 2025-12-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0067_projectwebconfiguration_discount_after_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='num_bedrooms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
