# Generated by Django 4.2.21 on 2025-12-31 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0068_alter_unit_num_bedrooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='eight_years_price',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='eight_years_price_equal',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='five_years_price_include_club',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='four_years_price',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='nine_years_price',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='one_year_price',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='seven_years_price',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='seven_years_price_equal',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='six_years_price',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='ten_years_price',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='three_years_price',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='two_years_price',
        ),
    ]
