# Generated by Django 4.2.21 on 2026-01-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0069_remove_unit_eight_years_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaspolicy',
            name='gas_num_pmts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gaspolicy',
            name='scheduling',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
