# Generated by Django 4.2.21 on 2026-01-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0071_attendancelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='can_change_years',
            field=models.BooleanField(default=False),
        ),
    ]
