# Generated by Django 4.2.21 on 2026-01-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0072_companyuser_can_change_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectwebconfiguration',
            name='allowed_years_for_sales',
            field=models.JSONField(blank=True, default=list, help_text='Optional list of allowed years for sales (1..12). Example: [1, 3, 5]'),
        ),
    ]
