# Generated by Django 4.2.21 on 2026-01-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0074_remove_salesrequestanalytical_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectwebconfiguration',
            name='one_dp_for_sales',
            field=models.BooleanField(default=False, help_text='If True: Sales flow uses one DP only (your business logic decides how to enforce).'),
        ),
    ]
