# Generated by Django 4.2.21 on 2026-01-08 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0075_projectwebconfiguration_one_dp_for_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('CompanyUser', 'Company User'), ('Developer', 'Developer'), ('Manager', 'Company Manager'), ('BusinessTeam', 'Business Team'), ('CompanyController', 'Company Controller'), ('CompanyFinanceManager', 'Company Finance Manager')], default='Company_User', max_length=100),
        ),
        migrations.CreateModel(
            name='CompanyFinanceManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToP.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
