# Generated by Django 4.2.21 on 2026-01-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0076_alter_user_role_companyfinancemanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='comp_type',
            field=models.JSONField(blank=True, default=list, help_text="List of active modules: ['native', 'erp', 'google_sheets']"),
        ),
    ]
