# Generated by Django 4.2.21 on 2026-01-16 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0076_alter_user_role_companyfinancemanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyViewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_pages', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit', models.BooleanField(default=False)),
                ('can_change_years', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SalesHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_dp_only', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SalesOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editable_unit_fields', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Uploader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='companyfinancemanager',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companyfinancemanager',
            name='user',
        ),
        migrations.RemoveField(
            model_name='companymanager',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companymanager',
            name='user',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='erpaccesskey',
            name='company',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='adj_contract_payment_plan',
            new_name='adj_status',
        ),
        migrations.RemoveField(
            model_name='salesrequest',
            name='erp_unit_code',
        ),
        migrations.RemoveField(
            model_name='salesrequestanalytical',
            name='erp_unit_code',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='adj_status_2',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='is_locked_for_erp_systems',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='is_locked_for_system',
        ),
        migrations.RemoveField(
            model_name='user',
            name='joining_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='company',
            name='comp_type',
            field=models.JSONField(blank=True, default=list, help_text="List of active modules: ['native', 'erp', 'google_sheets']"),
        ),
        migrations.AddField(
            model_name='unit',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businessanalysisteam',
            name='joining_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='businessanalysisteam',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_team_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CompanyController',
        ),
        migrations.DeleteModel(
            name='CompanyFinanceManager',
        ),
        migrations.DeleteModel(
            name='CompanyManager',
        ),
        migrations.DeleteModel(
            name='CompanyUser',
        ),
        migrations.DeleteModel(
            name='ERPAccessKey',
        ),
        migrations.AddField(
            model_name='uploader',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToP.company'),
        ),
        migrations.AddField(
            model_name='uploader',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uploader_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesteam',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_teams', to='ToP.company'),
        ),
        migrations.AddField(
            model_name='salesoperation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToP.company'),
        ),
        migrations.AddField(
            model_name='salesoperation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_ops_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saleshead',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToP.company'),
        ),
        migrations.AddField(
            model_name='saleshead',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heads', to='ToP.salesteam'),
        ),
        migrations.AddField(
            model_name='saleshead',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_head_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sales',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToP.company'),
        ),
        migrations.AddField(
            model_name='sales',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='ToP.salesteam'),
        ),
        migrations.AddField(
            model_name='sales',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manager',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToP.company'),
        ),
        migrations.AddField(
            model_name='manager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyviewer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToP.company'),
        ),
        migrations.AddField(
            model_name='companyviewer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='viewer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyadmin',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToP.company'),
        ),
        migrations.AddField(
            model_name='companyadmin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_admin_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
