# Generated by Django 4.2.21 on 2026-01-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0077_company_comp_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='adj_status_2',
            new_name='adj_status',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='adj_contract_payment_plan',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='is_locked_for_erp_systems',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='is_locked_for_system',
        ),
        migrations.AddField(
            model_name='unit',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
