# Generated by Django 4.2.21 on 2026-01-16 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0077_admin_companyadmin_companyviewer_manager_sales_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='sellable_area',
            new_name='gross_area',
        ),
    ]
