# Generated by Django 4.2.21 on 2026-01-19 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0078_rename_sellable_area_unit_gross_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constraints',
            name='annual_min',
        ),
        migrations.RemoveField(
            model_name='constraints',
            name='dp_plus_first_plus_second_plus_third_plus_forth_pmt',
        ),
        migrations.RemoveField(
            model_name='constraints',
            name='dp_plus_first_plus_second_plus_third_pmt',
        ),
        migrations.RemoveField(
            model_name='constraints',
            name='dp_plus_first_plus_second_pmt',
        ),
        migrations.RemoveField(
            model_name='constraints',
            name='dp_plus_first_pmt',
        ),
        migrations.RemoveField(
            model_name='constraints',
            name='first_year_min',
        ),
    ]
