# Generated by Django 4.2.21 on 2026-01-19 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0079_remove_constraints_annual_min_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectconfiguration',
            name='days_until_unblocking',
        ),
        migrations.RemoveField(
            model_name='projectconfiguration',
            name='variable_delivery_date',
        ),
    ]
