# Generated by Django 4.2.21 on 2026-01-15 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0079_delete_erpaccesskey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesrequest',
            name='erp_unit_code',
        ),
        migrations.RemoveField(
            model_name='salesrequestanalytical',
            name='erp_unit_code',
        ),
    ]
