# Generated by Django 4.2.21 on 2026-01-19 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0080_remove_projectconfiguration_days_until_unblocking_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectStanderdPayments',
        ),
    ]
