# Generated by Django 4.2.21 on 2026-01-19 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0081_delete_projectstanderdpayments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='secondary_views',
            new_name='secondary_view',
        ),
    ]
