# Generated by Django 4.2.21 on 2026-01-19 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0082_rename_secondary_views_unit_secondary_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='erp_url_unit',
            new_name='erp_approve_url',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='erp_url_unit_key',
            new_name='erp_approve_url_key',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='erp_url_units',
            new_name='erp_hold_url',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='erp_url_units_key',
            new_name='erp_hold_url_key',
        ),
    ]
