# Generated by Django 4.2.21 on 2026-01-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0083_rename_erp_url_unit_company_erp_approve_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
