# Generated by Django 4.2.21 on 2026-01-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0084_unit_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='creation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
