# Generated by Django 4.2.21 on 2026-01-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0085_alter_unit_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='num_bathrooms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
