# Generated by Django 4.2.21 on 2026-01-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0086_alter_unit_num_bathrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='auto_sync',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='auto_sync_timer',
            field=models.IntegerField(default=0),
        ),
    ]
