# Generated by Django 4.2.21 on 2026-01-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0087_company_auto_sync_company_auto_sync_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='last_auto_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
