# Generated by Django 4.2.21 on 2026-01-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0088_company_last_auto_sync_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='auto_sync_running',
            field=models.BooleanField(default=False),
        ),
    ]
