# Generated by Django 4.2.21 on 2026-01-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0089_company_auto_sync_running'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketunitdata',
            name='offering',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
