# Generated by Django 4.2.21 on 2026-01-28 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0090_marketunitdata_offering'),
    ]

    operations = [
        migrations.CreateModel(
            name='PivotUnitsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_html', models.TextField(blank=True, default='')),
                ('meta_text', models.TextField(blank=True, default='')),
                ('measures_text', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pivot_units_snapshot', to='ToP.company')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_pivot_units_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
