# Generated by Django 4.2.21 on 2026-01-28 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0091_pivotunitssnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERPUnitFieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provided_name', models.CharField(max_length=255)),
                ('needed_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_unit_field_mappings', to='ToP.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'provided_name'], name='ToP_erpunit_company_a7d18d_idx')],
                'unique_together': {('company', 'provided_name')},
            },
        ),
    ]
