"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-o)pxa0h09+i!_ef!g1xrd=8v5965yeqj)dtzp)wa-3gqf%a5s_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []



INSTALLED_APPS = [
    'daphne',
    'ToP',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'channels',
]

INSTALLED_APPS += ['rest_framework']

AUTH_USER_MODEL = 'ToP.User'


INACTIVITY_TIMEOUT_MINUTES = 30  # ← set your N here


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'ToP.middleware.InactiveUserLogoutMiddleware',


    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR, 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]



 

WSGI_APPLICATION = 'myproject.wsgi.application'
CHANNEL_LAYERS = {
    "default": {"BACKEND": "channels.layers.InMemoryChannelLayer"},
}



import pymysql
pymysql.install_as_MySQLdb()


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'top_3',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}




EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'mail.prometheus.com.eg'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False

EMAIL_HOST_USER = 'system@prometheus.com.eg'
EMAIL_HOST_PASSWORD = '0%]-u^b56z=WxCWh'

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
   
LOGIN_URL = '/login/'


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Cairo'

USE_I18N = True

USE_TZ = True

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent



STATIC_URL = 'static/'
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'), )

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



import os

# Media files (Uploaded by users)
MEDIA_URL = 'media/'  # Relative URL for media files
MEDIA_ROOT = BASE_DIR / 'media'  # Path where media files will be stored
ASGI_APPLICATION = 'myproject.asgi.application'

# Production-only Security Tweaks
if not DEBUG:
    # 1. Allow the server to tell Django it is actually HTTPS
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # 2. Allow WebSockets to connect from your domain
    CSRF_TRUSTED_ORIGINS = [
        'https://prometheus.com.eg', 
        'https://www.prometheus.com.eg'
    ]

    # 3. Standard Channels Config (In-Memory is fine for single-server cPanel)
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        },
    }



# ========= Google Sheets Integration =========

# Option A: Use a JSON key file
GOOGLE_SERVICE_ACCOUNT_FILE = os.getenv("GOOGLE_SERVICE_ACCOUNT_FILE", "django-gsheets-470712-1a13200c5b57.json")

# Your spreadsheet ID (from the full URL)
# Example URL: https://docs.google.com/spreadsheets/d/1krwkIYyxBWPGoDl4YeSDhLxRyVl6Hmk20WldgGpybSE/edit#gid=0
GOOGLE_SHEETS_SPREADSHEET_ID = os.getenv(
    "GOOGLE_SHEETS_SPREADSHEET_ID",
    "1krwkIYyxBWPGoDl4YeSDhLxRyVl6Hmk20WldgGpybSE"
)

# Default worksheet (tab) name
GOOGLE_SHEETS_WORKSHEET_TITLE = os.getenv("GOOGLE_SHEETS_WORKSHEET_TITLE", "Sheet1")

# Or use worksheet gid (numeric ID, like 0 in your URL)
GOOGLE_SHEETS_WORKSHEET_GID = os.getenv("GOOGLE_SHEETS_WORKSHEET_GID", "0")



# --- PUSHER CONFIGURATION ---
PUSHER_APP_ID = "2085101"
PUSHER_KEY = "c73fae7eaf62ece310af"
PUSHER_SECRET = "b576406220b2ff9cc13c"
PUSHER_CLUSTER = "eu"
